### ISSUE TITLE
Proposal for supporting banks allocated in NextBASIC

### ISSUE THREAD

**Issue by taylorza** [taylorza/zxn-inlineasm-doc#1]
Add a command line argument `-bN` which sets the target bank. Then from NextBASIC a combination of the `.$` DOT Command and a string variable can be used to pass in the bank number allocated in BASIC.

```
10 BANK NEW %a
20 b$ = "-b" + str$ (%a)
30 .$ asm b$
40 ; ....
50 ; ....
```

An alternative, I considered would be to extend the assemblers expression parser and use the NextOS API to get integer values, that would allow code like the following.

```
10 .asm
20 ;  bank %a
```

Where `%a` is the integer variable in from NextBASIC. This should be relatively straight forward using the `IDE_INTEGER_VAR` call. The one concern is that it might create the impression/expectation that integer variables can be accessed in this way at runtime.

Working example of the first option
![image](https://github.com/taylorza/zxn-inlineasm-doc/assets/13187192/99275869-6ed7-4e0e-97a3-49f50303022d)

**Comment by SimonGoodwin** [comment]
The second approach is effective.
