### ISSUE TITLE
Parsing of hexidecimal values

### ISSUE THREAD

**Issue by nic24-rgb** [taylorza/zxn-inlineasm-doc#2]
The statement "ld bc,2000h" correctly parses. The statement "ld de,affeh" does not parse correctly.

**Comment by taylorza** [comment]
@nic24-rgb - this is standard for the postfix notation for hex numbers. Because your hex number in the second case starts with a letter it could potentially be a label so in that case you need to prefix with a Zero.
`ld de, 0affeh`

**Comment by nic24-rgb** [comment]
GREAT! Thanks for clarification,

**Comment by nic24-rgb** [comment]
GREAT! Thanks for clarification,
