### ISSUE TITLE
Spurious label errors

### ISSUE THREAD

**Issue by SimonGoodwin** [taylorza/zxn-inlineasm-doc#4]
I am trying to write my third driver for NextZXOS using the very promising .asm

My PROFILE driver, assembled in Zeus is already part of the distro.

When I got about three quarters of the way through this one I started to get spurious errors about undefined and duplicate labels when the label definitions hadn’t changed.

The total driver code and data size limit is 512 bytes and I’ve not reached that yet, or used any labels more than seven bytes long, so it’s hardly large - about 10K of commented source and BASIC test PROCs.

After two days experimenting with old versions and exits, and updating asm for the third time to the latest (which made no difference) I tentatively conclude that there’s an undocumented and untrapped limit on the total length of symbols; when that is reached, misleading error reports prevent successful assembly.

Meanwhile I am reluctantly considering shifting the project to Odin just so I can finish and test it. I’d love to be the first to release a non-trivial and useful driver written with your .asm though.

I am willing to privately share my unfinished code in confidence if that helps you and others, but certainly not to post it here. After it works and is documented it will be uploaded to GetIt.

You can contact me directly via SimonNGoodwin on FB messenger or a little slower via my web page http://simon.mooli.org.uk

Thanks for supporting Next.

**Comment by taylorza** [comment]
Thanks Simon, there is definitely a limit on the number of symbols, the next release of the assembler has the symbol table shifted out of the 8K memory area of the DOT Command into a dedicated bank. I look forward to seeing a non-trivial project developed with the assembler to help iron out the cases I potentially missed.

**Comment by SimonGoodwin** [comment]
Thanks, I shall do some diagrams in the meantime. If you drop me an email address I’ll share WIP with you privately but in any case look forward to re-testing on 0.4 soon; hope it goes well and you find room for an extra diagnostic or two. 🤓

I’ve tested a dozen or so Z80 assemblers on Next alone and early on even used 1982’s ACS Ultraviolet on Next for the BASIC integration you now provide; uSource also had promise but clashes with NextZXOS or default ports (or both) so yours is currently my fave for little hacks and nearly ripe for larger ones.

If you were to give the subdirectory a different name from the executable next time that’ll make unpacking into dot a bit simpler - unlike directories with type metadata, FAT can’t cope with directories and data files sharing a name so the copy out to dot after unzipping there confounds the browser.

— 
http://simon.mooli.org.uk

**Comment by taylorza** [comment]
This has been addressed in v0.4. pending confirmation from your testing before closing this item.

**Comment by SimonGoodwin** [comment]
Additional labels are now accepted and duplicate or missing ones are being reported.
